# Generated by Django 4.1.3 on 2022-12-21 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='facebook',
            field=models.URLField(default='https://www.facebook.com/profile.php?id=100050463701271', unique=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio', to=settings.AUTH_USER_MODEL),
        ),
    ]
