# Generated by Django 4.1.3 on 2023-01-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contactinfo_facebook_alter_bio_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='linkedin',
            new_name='linkin',
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(default='https://i.imgur.com/4ZQZQ2u.jpg'),
        ),
    ]
