# Generated by Django 4.1.3 on 2023-01-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_linkedin_contactinfo_linkin_post_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
    ]
