# Generated by Django 4.1.3 on 2023-01-25 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_remove_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coauthour',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fakenews', to=settings.AUTH_USER_MODEL),
        ),
    ]
