# Generated by Django 4.1.3 on 2023-01-25 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_post_coauthour_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='coauthour',
            new_name='coauthor',
        ),
    ]
