# Generated by Django 4.1.3 on 2023-01-25 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_coauthour_post_coauthor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='coauthor',
        ),
    ]
